packages:
  - apps/*
  - packages/*
onlyBuiltDependencies:
  - "@prisma/engines"
  - prisma
  - esbuild
  - embedded-postgres

  - "@embedded-postgres/darwin-arm64"
  - "@embedded-postgres/linux-x64"
